spring:
  datasource:
    url: jdbc:h2:file:~/ws
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
      path: /db
  jpa:
    hibernate:
      ddl-auto: update